#导航栏
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    电影: /movies/ || fas fa-video
  个人项目: http://chat.beyonduniverse.club || fas fa-atlas
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart


# 代码块
# highlight_theme: mac-light
# highlight_copy: true

# 社交网络
social:
  fab fa-github: https://github.com/christopherzh || Github

# 头像
avatar:
  img: /img/christopher.png

footer:
  owner:
    enable: true
    since: 2022

# dark mode
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: false

# 网站统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 背景丝带
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false  #设置是否每次点击都更换綵带
  mobile: true # false 手机端不显示 true 手机端显示

# 点击出现爱心
click_heart:
  enable: true
  mobile: true

  # 主页subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (循环打字)
  loop: true
  # source 调用第三方服务
  # source: false 关闭调用
  # source: 1  调用一言网的一句话（简体） https://hitokoto.cn/
  # source: 2  调用一句网（简体） http://yijuzhan.com/
  # source: 3  调用今日诗词（简体） https://www.jinrishici.com/
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: false
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
    - Do not go gentle into that good night
    - Old age should burn and rave at close of the day
    - Rage, rage against the dying of the light

# 加载动画 Loading Animation
preloader: true

default_top_img: /img/earth.jpg


aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/christopherzh
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works
